<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace financecalculator;

use \php\_Boot\HxAnon;
use \php\Boot;

class FinCalc {
	/**
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @param float $presentValue
	 * @param int $numPeriods
	 * @param float $interestRate
	 * @param int $timesCompoundedPerPeriod
	 * @param float $depositAmount
	 * @param bool $depositAtBeginning
	 * 
	 * @return object
	 */
	public function futureValue ($presentValue, $numPeriods, $interestRate, $timesCompoundedPerPeriod, $depositAmount, $depositAtBeginning) {
		#/src/financecalculator/FinCalc.hx:8: characters 9-39
		$ir = $interestRate / 100.0;
		#/src/financecalculator/FinCalc.hx:9: characters 9-64
		$fvps = $presentValue * ((1 + $ir) ** $numPeriods);
		#/src/financecalculator/FinCalc.hx:10: characters 9-37
		$fv = $depositAmount / $ir;
		#/src/financecalculator/FinCalc.hx:11: characters 9-46
		$fv *= ((1 + $ir) ** $numPeriods) - 1.0;
		#/src/financecalculator/FinCalc.hx:12: lines 12-14
		if ($depositAtBeginning) {
			#/src/financecalculator/FinCalc.hx:13: characters 13-29
			$fv *= 1.0 + $ir;
		}
		#/src/financecalculator/FinCalc.hx:15: characters 9-69
		$totalDeposits = $numPeriods * $depositAmount + $presentValue;
		#/src/financecalculator/FinCalc.hx:16: characters 9-37
		$futureValue = $fv + $fvps;
		#/src/financecalculator/FinCalc.hx:17: characters 9-57
		$totalInterest = $futureValue - $totalDeposits;
		#/src/financecalculator/FinCalc.hx:18: characters 9-59
		$futureValue = floor($futureValue * 100.0 + 0.5) / 100.0;
		#/src/financecalculator/FinCalc.hx:19: characters 9-63
		$totalInterest = floor($totalInterest * 100.0 + 0.5) / 100.0;
		#/src/financecalculator/FinCalc.hx:20: characters 9-63
		$totalDeposits = floor($totalDeposits * 100.0 + 0.5) / 100.0;
		#/src/financecalculator/FinCalc.hx:21: characters 9-99
		return new HxAnon([
			"futureValue" => $futureValue,
			"totalInterest" => $totalInterest,
			"totalDeposits" => $totalDeposits,
		]);
	}
}

Boot::registerClass(FinCalc::class, 'financecalculator.FinCalc');
